log4r_config:
  # define all loggers ...
  loggers:
    - name      : production
      level     : DEBUG
      trace     : 'true'
      outputters :
      - datefile
    - name      : development
      level     : DEBUG
      trace     : 'true'
      outputters :
      - datefile

  # define all outputters (incl. formatters)
  outputters:
  - type: DateFileOutputter
    name: datefile
    dirname: "log"
    filename: "share_and_care.log" # notice the file extension is needed! 
    formatter:
      date_pattern: '%Y-%m-%d %H:%M:%S,%L'
      pattern     : '%d %C [%5l] :: %m'
      type        : PatternFormatter